package com.comp;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;

public class TestVis extends CustomComponent {
 
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheet_11;
	@AutoGenerated
	private RichTextArea richTextArea_2;
	@AutoGenerated
	private Button button_2;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TestVis() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tabSheet_11
		tabSheet_11 = buildTabSheet_11();
		mainLayout.addComponent(tabSheet_11);
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_11() {
		// common part: create layout
		tabSheet_11 = new TabSheet();
		tabSheet_11.setImmediate(true);
		tabSheet_11.setWidth("820px");
		tabSheet_11.setHeight("340px");
		
		// button_2
		button_2 = new Button();
		button_2.setCaption("Button");
		button_2.setImmediate(false);
		button_2.setWidth("-1px");
		button_2.setHeight("-1px");
		tabSheet_11.addTab(button_2, "Tab", null);
		
		// richTextArea_2
		richTextArea_2 = new RichTextArea();
		richTextArea_2.setImmediate(false);
		richTextArea_2.setWidth("-1px");
		richTextArea_2.setHeight("-1px");
		tabSheet_11.addTab(richTextArea_2, "Tab", null);
		
		return tabSheet_11;
	}

}
